default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: simulation #backend_development

test:
  <<: *default
  database: simulation_test #backend_test

production:
  <<: *default
  database: simulation #backend
